'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const note_endpoint_1 = require("../../endpoints/api/note_endpoint");
const passport = require("passport");
require('../../config/passport')(passport);
const index_1 = require("../../schemas/index");
const validator = require('../../schemas/notes/index');
let auth = passport.authenticate('jwt', { session: false });
let authLog = passport.authenticate('local', { session: false });
router.post('/mod/add-tags', auth, validator(index_1.Schemas.Notes.ADD_TAGS_SCHEMA), note_endpoint_1.default.addTags);
router.post('/mod/change-links', auth, validator(index_1.Schemas.Notes.CHANGE_LINKS_SCHEMA), note_endpoint_1.default.changeLinks);
router.post('/mod/change-title', auth, validator(index_1.Schemas.Notes.CHANGE_TITLE_SCHEMA), note_endpoint_1.default.changeTitle);
router.post('/mod/change-text', auth, validator(index_1.Schemas.Notes.CHANGE_TEXT_SCHEMA), note_endpoint_1.default.changeText);
router.put('/create', auth, validator(index_1.Schemas.Notes.CREATE_NOTE_SCHEMA), note_endpoint_1.default.createNote);
router.delete('/:title', auth, note_endpoint_1.default.removeNote);
router.post('/mod/remove-tags', auth, validator(index_1.Schemas.Notes.REMOVE_TAGS_SCHEMA), note_endpoint_1.default.removeTagsFromNote);
router.post('/by-tags/and/with-date', auth, validator(index_1.Schemas.Notes.NOTES_BY_TAGS_SCHEMA), note_endpoint_1.default.selectNotesMinWithDateByTagsAnd);
router.post('/by-tags/and', auth, validator(index_1.Schemas.Notes.NOTES_BY_TAGS_SCHEMA), note_endpoint_1.default.selectNotesMinByTagsAnd);
router.post('/by-tags/or/with-date', auth, validator(index_1.Schemas.Notes.NOTES_BY_TAGS_SCHEMA), note_endpoint_1.default.selectNotesMinWithDateByTagsOr);
router.post('/by-tags/or', auth, validator(index_1.Schemas.Notes.NOTES_BY_TAGS_SCHEMA), note_endpoint_1.default.selectNotesMinByTagsOr);
router.post('/by-tile-reg', auth, validator(index_1.Schemas.Notes.NOTES_BY_TITLE_REG_SCHEMA), note_endpoint_1.default.selectNotesMinByTitleReg);
router.post('/by-text', auth, validator(index_1.Schemas.Notes.NOTES_BY_TEXT_SCHEMA), note_endpoint_1.default.selectNotesMinByTextReg);
router.post('/by-tile-reg/with-date', auth, validator(index_1.Schemas.Notes.NOTES_BY_TITLE_REG_SCHEMA), note_endpoint_1.default.selectNotesMinWithDateByTitleReg);
router.post('/by-text/with-date', auth, validator(index_1.Schemas.Notes.NOTES_BY_TEXT_SCHEMA), note_endpoint_1.default.selectNotesMinWithDateByTextReg);
router.post('/by-isdone', auth, validator(index_1.Schemas.Notes.NOTES_BY_ISDONE_SCHEMA), note_endpoint_1.default.selectNotesMinByIsDone);
router.post('/by-isdone/with-date', auth, validator(index_1.Schemas.Notes.NOTES_BY_ISDONE_SCHEMA), note_endpoint_1.default.selectNotesMinWithDateByIsDone);
router.post('/mod/set-done', validator(index_1.Schemas.Notes.SET_DONE_SCHEMA), auth, note_endpoint_1.default.setDone);
router.get('/all/min', auth, note_endpoint_1.default.selectNotesMin);
router.post('/all/min', auth, note_endpoint_1.default.selectNotesMin);
router.get('/all/min/with-date', auth, note_endpoint_1.default.selectNotesMinWithDate);
router.post('/all/min/with-date', auth, note_endpoint_1.default.selectNotesMinWithDate);
router.get('/:title', auth, note_endpoint_1.default.selectNoteByTitle);
exports.default = router;
//# sourceMappingURL=notes.js.map